In [1]:
import ipywidgets as widgets
from ipywidgets import Output
from IPython.display import display

out = Output()           # I created this here because I will use it in several cells

In [2]:
import pandas as pd
weather = pd.read_csv('data/TN/weather3.csv')
weather

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,1/12/08,Albury,13.4,22.9,0.6,NaN,NaN,W,44,W,...,22,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2/12/08,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44,NNW,...,25,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,3/12/08,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46,W,...,30,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,4/12/08,Albury,9.2,28.0,0.0,NaN,NaN,NE,24,SE,...,16,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,5/9/09,Moree,12.9,22.0,12.8,6.6,6.5,SW,31,NW,...,48,1016.1,1014.2,8.0,4.0,15.4,21.0,Yes,0.0,No
5,6/9/09,Moree,4.6,23.2,0.0,3.8,11.2,NNW,31,NE,...,29,1018.4,1013.7,1.0,1.0,14.9,22.3,No,0.0,No
6,7/9/09,Moree,9.1,19.6,0.0,4.8,0.0,NNE,48,NNE,...,79,1010.8,1007.8,7.0,8.0,18.4,17.7,No,4.0,Yes
7,8/9/09,Moree,5.5,21.3,4.0,1.6,8.7,WNW,37,W,...,33,1012.4,1010.4,2.0,5.0,13.3,19.7,Yes,0.0,No
8,9/9/09,Moree,3.6,20.2,0.0,3.4,11.1,W,37,W,...,26,1016.6,1013.6,1.0,2.0,13.7,19.7,No,0.0,No
9,10/9/09,Moree,4.1,21.7,0.0,4.6,11.3,WNW,31,NNW,...,20,1019.3,1016.9,0.0,1.0,14.1,20.9,No,0.0,No
10,15/4/13,Penrith,12.6,26.8,0.2,NaN,NaN,SE,24,ESE,...,52,NaN,NaN,NaN,NaN,17.3,26.4,No,18.4,Yes
11,16/4/13,Penrith,16.0,20.7,18.4,NaN,NaN,SSE,22,NaN,...,81,NaN,NaN,NaN,NaN,16.9,19.7,Yes,0.2,No
12,17/4/13,Penrith,12.5,23.7,0.2,NaN,NaN,ESE,20,NaN,...,54,NaN,NaN,NaN,NaN,18.9,23.0,No,0.2,No
13,18/4/13,Penrith,13.5,25.6,0.2,NaN,NaN,ESE,31,NNE,...,59,NaN,NaN,NaN,NaN,18.9,22.0,No,0.2,No
14,19/4/13,Penrith,12.1,21.4,0.2,NaN,NaN,S,48,S,...,36,NaN,NaN,NaN,NaN,15.8,20.7,No,7.0,Yes
15,20/4/13,Penrith,13.0,18.4,7.0,NaN,NaN,S,39,SSW,...,76,NaN,NaN,NaN,NaN,15.7,18.3,Yes,11.4,Yes
16,5/10/17,Sydney,16.5,23.4,0.0,5.0,9.6,NNE,41,W,...,64,1018.8,1013.1,4.0,1.0,19.5,22.6,No,0.0,No
17,6/10/17,Sydney,18.0,22.1,0.0,6.6,4.7,SSW,39,SSW,...,46,1013.5,1015.8,6.0,3.0,18.9,20.3,No,0.0,No
18,7/10/17,Sydney,13.7,22.0,0.0,6.2,8.7,SSW,43,SW,...,46,1023.4,1021.2,6.0,3.0,16.2,21.1,No,0.0,No
19,8/10/17,Sydney,13.0,21.4,0.0,4.8,2.3,ENE,31,WNW,...,64,1020.7,1016.0,7.0,8.0,16.6,19.6,No,NaN,NaN
20,4/10/19,GoldCoast,14.3,25.7,0.0,NaN,NaN,NNE,41,NW,...,68,1024.1,1019.9,NaN,NaN,21.4,22.9,No,0.0,No
21,5/10/19,GoldCoast,14.7,25.1,0.0,NaN,NaN,SSE,70,NNW,...,81,1020.0,1019.0,NaN,NaN,23.2,20.9,No,0.0,No
22,6/10/19,GoldCoast,15.9,24.4,0.0,NaN,NaN,NE,31,SSE,...,71,1021.9,1016.7,NaN,NaN,21.8,23.1,No,0.0,No
23,7/10/19,GoldCoast,18.9,26.3,0.0,NaN,NaN,NNE,41,N,...,82,1015.4,1010.1,NaN,NaN,24.3,24.0,No,0.0,No
24,8/10/19,GoldCoast,19.4,28.9,0.0,NaN,NaN,SE,59,NNW,...,82,1011.7,1006.9,NaN,NaN,24.5,25.1,No,0.0,No
25,1/7/08,Brisbane,10.3,25.2,0.0,1.4,9.5,WNW,26,SSW,...,37,1019.6,1014.8,0.0,1.0,14.9,24.6,No,0.0,No
26,2/7/08,Brisbane,8.1,22.9,0.0,2.0,9.8,W,30,W,...,30,1018.8,1015.0,0.0,0.0,16.2,22.4,No,0.0,No
27,3/7/08,Brisbane,9.7,22.4,0.0,5.8,9.4,E,22,SW,...,52,1021.4,1019.1,1.0,4.0,15.4,21.3,No,0.8,No
28,4/7/08,Brisbane,11.8,20.0,0.8,1.8,1.1,SW,24,SW,...,53,1023.5,1021.7,7.0,7.0,14.1,19.6,No,0.0,No

In [3]:
weather[weather.Location == 'Brisbane']

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
25,1/7/08,Brisbane,10.3,25.2,0.0,1.4,9.5,WNW,26,SSW,...,37,1019.6,1014.8,0.0,1.0,14.9,24.6,No,0.0,No
26,2/7/08,Brisbane,8.1,22.9,0.0,2.0,9.8,W,30,W,...,30,1018.8,1015.0,0.0,0.0,16.2,22.4,No,0.0,No
27,3/7/08,Brisbane,9.7,22.4,0.0,5.8,9.4,E,22,SW,...,52,1021.4,1019.1,1.0,4.0,15.4,21.3,No,0.8,No
28,4/7/08,Brisbane,11.8,20.0,0.8,1.8,1.1,SW,24,SW,...,53,1023.5,1021.7,7.0,7.0,14.1,19.6,No,0.0,No

In [4]:
weather_cities = ['All'] + list(weather.Location.unique())
#weather_cities
min_temp = ['All'] + list(weather.MinTemp.unique())
#min_temp

In [5]:
dd_city = widgets.Dropdown(options = weather_cities)
#display(dd_city)
dd_min_temp = widgets.Dropdown(options = min_temp)
#display(dd_min_temp)

The query only filters by the drop-down, which was recently changed. I want it to work on both values together. So what I really need is a new function to do the querying and have the observe handlers call it, passing the values for the query parameters. The dd_city observer method will call this new method, query_weather, passing the new value from the bunch, but also the current value of the dd_min_temp drop-down, and the dd_min_temp observer method will call query_weather as well, except with the value of the dd_city drop-down and then its new value.

In [6]:
def query_weather(city, min_temp):
    city_filter = weather if city =='ALL' else weather[weather.Location == city]
    min_temp_filter = city_filter if min_temp == 'All' else city_filter[city_filter.MinTemp == min_temp] 
    with out:
        display(min_temp_filter)

In [7]:
#def dd_city_observer(bunch):          #I'll create a function for the observer handler that will filter the data frame by the value selected in the drop-down.
#    out.clear_output()                #  To clear this output widget each time the drop-down changes, I'll add a call to the clear_output method of the output widget in the observe handler
#    with out:                         # I'm going to tell the output widget to capture the output of the data frame by calling display inside of a with block.
#        display(weather[weather.Location == bunch.new])
        
#def dd_min_temp_observer(bunch):
#    out.clear_output()                
#    with out:                       
#        display(weather[weather.MinTemp == bunch.new])

In [8]:
def dd_city_observer(bunch):
    out.clear_output()
    query_weather(bunch.new, dd_min_temp.value)
    
def dd_min_temp_observer(bunch):
    out.clear_output()
    query_weather(dd_city.value, bunch.new)

 I'll register the observer with the city drop-down and make sure that observe sends a bunch regarding the values.

In [9]:
dd_city.observe(dd_city_observer, names = 'value')       
dd_min_temp.observe(dd_min_temp_observer, names = 'value')

In [10]:
display(dd_city)
display(dd_min_temp)

Dropdown(options=('All', 'Albury', 'Moree', 'Penrith', 'Sydney', 'GoldCoast', 'Brisbane'), value='All')

Dropdown(options=('All', 13.4, 7.4, 12.9, 9.2, 4.6, 9.1, 5.5, 3.6, 4.1, 12.6, 16.0, 12.5, 13.5, 12.1, 13.0, 16…

For refereshing the table each time and clearing the last one : >>> adding widget __Output__ that need to be imported

In [11]:
display(out)

Output()

### Finally I could bring tempretures filtered by cities!! why? Review this one later